
name: CI
on:
  push:
    branches: [ production ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      -  name: Setup Node.js environment
         uses: actions/setup-node@v2.4.0
         with:
          node-version: 14.x
          
      -  name: Install dependencies
         run: yarn
         
      -  name: Run build
         run: yarn build
         
      -  name: Copy disto do Digital Ocean
         uses: appleboy/scp-action@master
         with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USER}}
            port: ${{secrets.SSH_PORT}}
            key: ${{secrets.SSH_KEY}}
            source: ".,!node_modules"
            target: "~/backend/server"
            
      -  name: Run production scripts
         uses: appleboy/ssh-action@master
         with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USER}}
            port: ${{secrets.SSH_PORT}}
            key: ${{secrets.SSH_KEY}}
            script: |
              cd ~/backend/server
              yarn
              .node_modules/.bin/typeorm migration:run
              pm2 restart ags001-api
            
            
            
         
